version: '3.8'

services:
  php:
    build: ./docker/php
    container_name: tax_php
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html

  nginx:
    image: nginx:alpine
    container_name: tax_nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php